#!/bin/bash
mkdir -p ~/proje1
cd ~/proje1 || exit

touch not1.txt not2.txt not3.txt

echo "Bu birinci nottur." > not1.txt
echo "Bu ikinci nottur." > not2.txt
echo "Bu üçüncü nottur." > not3.txt

cat not1.txt
cat not2.txt
cat not3.txt

ls -l
chmod 750 not3.txt
ls -l not3.txt

echo "Man sayfasında arama yapılabilir: (manuel açılır)"
echo "Örnek: man chmod ve ardından /permission"

echo "Komutların yolları:"
which ls
which echo
which man

echo "Ağaç görünümü:"
tree -C .

